/*
 * home.java
 * Created on Sep 7, 2010, 3:29:14 PM
 */

package e2a;

import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author abdallah abuouf
 *  http://abuouf.wordpress.com
 */
public class home extends javax.swing.JFrame {
String arabic;

    public home() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
SwingUtilities.updateComponentTreeUI( this );
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenu = new javax.swing.JPopupMenu();
        copypMenuItem = new javax.swing.JMenuItem();
        cutpMenuItem = new javax.swing.JMenuItem();
        clearpMenuItem = new javax.swing.JMenuItem();
        selectMenuItem = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        ATextArea = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        copyButton = new javax.swing.JButton();
        cutButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        copyMenuItem = new javax.swing.JMenuItem();
        cutMenuItem = new javax.swing.JMenuItem();
        clearMenuItem = new javax.swing.JMenuItem();
        selectaallMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        webMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        copypMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Copy-icon.png"))); // NOI18N
        copypMenuItem.setText("Copy");
        copypMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copypMenuItemActionPerformed(evt);
            }
        });
        PopupMenu.add(copypMenuItem);

        cutpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Cut-icon.png"))); // NOI18N
        cutpMenuItem.setText("Cut");
        cutpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutpMenuItemActionPerformed(evt);
            }
        });
        PopupMenu.add(cutpMenuItem);

        clearpMenuItem.setText("Clear");
        clearpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearpMenuItemActionPerformed(evt);
            }
        });
        PopupMenu.add(clearpMenuItem);

        selectMenuItem.setText("Select all");
        selectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMenuItemActionPerformed(evt);
            }
        });
        PopupMenu.add(selectMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E2A");
        setLocationByPlatform(true);

        ATextArea.setColumns(20);
        ATextArea.setRows(5);
        ATextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ATextAreaMouseReleased(evt);
            }
        });
        ATextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ATextAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ATextAreaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ATextAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(ATextArea);

        jToolBar1.setRollover(true);

        copyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Copy-icon.png"))); // NOI18N
        copyButton.setToolTipText("Copy");
        copyButton.setFocusable(false);
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(copyButton);

        cutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Cut-icon.png"))); // NOI18N
        cutButton.setToolTipText("Cut");
        cutButton.setFocusable(false);
        cutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cutButton);

        clearButton.setText("clear");
        clearButton.setFocusable(false);
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(clearButton);

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Information-icon.png"))); // NOI18N
        helpButton.setToolTipText("About");
        helpButton.setFocusable(false);
        helpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(helpButton);

        fileMenu.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/close.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Copy-icon.png"))); // NOI18N
        copyMenuItem.setText("Copy Arabic");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Cut-icon.png"))); // NOI18N
        cutMenuItem.setText("Cut Arabic");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        clearMenuItem.setText("Clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(clearMenuItem);

        selectaallMenuItem.setText("Select all");
        selectaallMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectaallMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(selectaallMenuItem);

        jMenuBar1.add(editMenu);

        helpMenu.setText("About");

        webMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Globe-icon.png"))); // NOI18N
        webMenuItem.setText("Web Site");
        webMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(webMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e2a/Information-icon.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        about();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
/*

 */
    private void ATextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATextAreaMouseReleased
        if(evt.getButton()==MouseEvent.BUTTON3){
        PopupMenu.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_ATextAreaMouseReleased

    private void copypMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copypMenuItemActionPerformed
        ATextArea.copy();
    }//GEN-LAST:event_copypMenuItemActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
       ATextArea.selectAll();
        ATextArea.copy();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
       ATextArea.selectAll();
        ATextArea.copy();
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        ATextArea.selectAll();
        ATextArea.cut();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutButtonActionPerformed
        ATextArea.selectAll();
        ATextArea.cut();
    }//GEN-LAST:event_cutButtonActionPerformed

    private void cutpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutpMenuItemActionPerformed
        ATextArea.cut();
    }//GEN-LAST:event_cutpMenuItemActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void clearpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearpMenuItemActionPerformed
        clear();
    }//GEN-LAST:event_clearpMenuItemActionPerformed

    private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
        clear();
    }//GEN-LAST:event_clearMenuItemActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
    }//GEN-LAST:event_editMenuActionPerformed

    private void selectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMenuItemActionPerformed
        ATextArea.requestFocus();
        ATextArea.selectAll();
    }//GEN-LAST:event_selectMenuItemActionPerformed

    private void webMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webMenuItemActionPerformed
        try {
            try {
                java.awt.Desktop.getDesktop().browse(new URI("http://www.abuouf.wordpress.com"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_webMenuItemActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        about();
    }//GEN-LAST:event_helpButtonActionPerformed

    private void selectaallMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectaallMenuItemActionPerformed
        ATextArea.requestFocus();
        ATextArea.selectAll();
    }//GEN-LAST:event_selectaallMenuItemActionPerformed

    private void ATextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATextAreaKeyPressed

    }//GEN-LAST:event_ATextAreaKeyPressed

    private void ATextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATextAreaKeyReleased
                  String tmp=ATextArea.getText();
        arabic=cEtoA(tmp);
        ATextArea.setText(arabic);
    }//GEN-LAST:event_ATextAreaKeyReleased

    private void ATextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATextAreaKeyTyped

    }//GEN-LAST:event_ATextAreaKeyTyped
public String cEtoA(String tmp){
String after="";
int ascii;
char []ch={'ج','|','د','^','_','ذ','ش','ﻻ','ؤ','ي','ث','ب','ل','ا','ه','ت','ن','م','ة','ى','خ','ح','ض','ق','س','ف','ع','ر','ص','ء','غ','ئ'};
for(int i=0;i<tmp.length();i++){
char c=Character.toLowerCase(tmp.charAt(i));
    ascii=(int)c;
if(ascii>90&&ascii<123){
after+=ch[ascii-91]+"";
}else if(ascii==44){
after+="و";
}
else if(ascii==59){
after+="ك";
}else if(ascii==39){
after+="ط";
}else if(ascii==47){
after+="ظ";
}
else if(ascii==46){
after+="ز";
}else{
after+=tmp.charAt(i);
}
}

return after;

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ATextArea;
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton clearButton;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JMenuItem clearpMenuItem;
    private javax.swing.JButton copyButton;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem copypMenuItem;
    private javax.swing.JButton cutButton;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem cutpMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton helpButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem selectMenuItem;
    private javax.swing.JMenuItem selectaallMenuItem;
    private javax.swing.JMenuItem webMenuItem;
    // End of variables declaration//GEN-END:variables



    private void clear() {
        ATextArea.setText("");
    }

    private void about() {
        JOptionPane.showMessageDialog(ATextArea,"E2A V2.0 \nEnglish to Arabic \n it is a program for write arabic by \n pc didn't support arabic for keyboard \n Under Waqf license","E2A",JOptionPane.INFORMATION_MESSAGE);
    }

}
